# This file was auto-generated by salt's setup on Monday, 21 December 2015 @ 03:12:10 UTC.

ROOT_DIR = None
CONFIG_DIR = None
CACHE_DIR = None
SOCK_DIR = None
SRV_ROOT_DIR= None
BASE_FILE_ROOTS_DIR = None
BASE_PILLAR_ROOTS_DIR = None
BASE_MASTER_ROOTS_DIR = None
LOGS_DIR = None
PIDFILE_DIR = None
